//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgileQuoteAdmin.AgileAdminService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AgileAdminService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteRentalSparsService", ReplyAction="http://tempuri.org/IService1/DeleteRentalSparsServiceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/DeleteRentalSparsServiceExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        string DeleteRentalSparsService(int RentalSparsId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateRentalSparsService", ReplyAction="http://tempuri.org/IService1/UpdateRentalSparsServiceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/UpdateRentalSparsServiceExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        int UpdateRentalSparsService(AgileQuoteAdminProperty.Property.RentalSparsProperty oRentalSpars);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SingleRentalSparsService", ReplyAction="http://tempuri.org/IService1/SingleRentalSparsServiceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/SingleRentalSparsServiceExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        AgileQuoteAdminProperty.Property.RentalSparsProperty SingleRentalSparsService(int RentalSparsId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RentalSparsListService", ReplyAction="http://tempuri.org/IService1/RentalSparsListServiceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/RentalSparsListServiceExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        System.Collections.Generic.List<AgileQuoteAdminProperty.Property.RentalSparsProperty> RentalSparsListService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertRentalSparsService", ReplyAction="http://tempuri.org/IService1/InsertRentalSparsServiceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/InsertRentalSparsServiceExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        int InsertRentalSparsService(AgileQuoteAdminProperty.Property.RentalSparsProperty oRentalSpars);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRoleListService", ReplyAction="http://tempuri.org/IService1/GetRoleListServiceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/GetRoleListServiceExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        System.Collections.Generic.List<AgileQuoteAdminProperty.Property.RoleProperty> GetRoleListService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSingleRoleRecordService", ReplyAction="http://tempuri.org/IService1/GetSingleRoleRecordServiceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/GetSingleRoleRecordServiceExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        AgileQuoteAdminProperty.Property.RoleProperty GetSingleRoleRecordService(int RoleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertRoleRecordService", ReplyAction="http://tempuri.org/IService1/InsertRoleRecordServiceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/InsertRoleRecordServiceExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        string InsertRoleRecordService(AgileQuoteAdminProperty.Property.RoleProperty oRoleProperty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateRoleService", ReplyAction="http://tempuri.org/IService1/UpdateRoleServiceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/UpdateRoleServiceExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        string UpdateRoleService(AgileQuoteAdminProperty.Property.RoleProperty oRoleProperty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteRoleService", ReplyAction="http://tempuri.org/IService1/DeleteRoleServiceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/DeleteRoleServiceExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        string DeleteRoleService(int RoleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCurrencyListService", ReplyAction="http://tempuri.org/IService1/GetCurrencyListServiceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/GetCurrencyListServiceExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        System.Collections.Generic.List<AgileQuoteAdminProperty.Property.CurrencyProperty> GetCurrencyListService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSingleCurrencyRecordService", ReplyAction="http://tempuri.org/IService1/GetSingleCurrencyRecordServiceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/GetSingleCurrencyRecordServiceExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        AgileQuoteAdminProperty.Property.CurrencyProperty GetSingleCurrencyRecordService(int CurrencyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertCurrencyRecordService", ReplyAction="http://tempuri.org/IService1/InsertCurrencyRecordServiceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/InsertCurrencyRecordServiceExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        string InsertCurrencyRecordService(AgileQuoteAdminProperty.Property.CurrencyProperty oCurrencyProperty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCurrencyService", ReplyAction="http://tempuri.org/IService1/UpdateCurrencyServiceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/UpdateCurrencyServiceExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        string UpdateCurrencyService(AgileQuoteAdminProperty.Property.CurrencyProperty oCurrencyProperty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCurrrencyService", ReplyAction="http://tempuri.org/IService1/DeleteCurrrencyServiceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/DeleteCurrrencyServiceExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        string DeleteCurrrencyService(int CurrencyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSalesOrganizationListService", ReplyAction="http://tempuri.org/IService1/GetSalesOrganizationListServiceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/GetSalesOrganizationListServiceExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        System.Collections.Generic.List<AgileQuoteAdminProperty.Property.SalesOrganizationProperty> GetSalesOrganizationListService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSalesOrganizationRecord", ReplyAction="http://tempuri.org/IService1/GetSalesOrganizationRecordResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/GetSalesOrganizationRecordExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        AgileQuoteAdminProperty.Property.SalesOrganizationProperty GetSalesOrganizationRecord(int SalesOrgCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertRecordService", ReplyAction="http://tempuri.org/IService1/InsertRecordServiceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/InsertRecordServiceExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        string InsertRecordService(AgileQuoteAdminProperty.Property.SalesOrganizationProperty OsalesOrganizationProperty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateRecordService", ReplyAction="http://tempuri.org/IService1/UpdateRecordServiceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/UpdateRecordServiceExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        string UpdateRecordService(AgileQuoteAdminProperty.Property.SalesOrganizationProperty OsalesOrganizationProperty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteRecordService", ReplyAction="http://tempuri.org/IService1/DeleteRecordServiceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/DeleteRecordServiceExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        string DeleteRecordService(int SalesOrgCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMaterialListService", ReplyAction="http://tempuri.org/IService1/GetMaterialListServiceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/GetMaterialListServiceExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        System.Collections.Generic.List<AgileQuoteAdminProperty.Property.MaterialProperty> GetMaterialListService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMaterialListByID", ReplyAction="http://tempuri.org/IService1/GetMaterialListByIDResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/GetMaterialListByIDExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        AgileQuoteAdminProperty.Property.MaterialProperty GetMaterialListByID(int oMaterialId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertMaterial", ReplyAction="http://tempuri.org/IService1/InsertMaterialResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/InsertMaterialExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        int InsertMaterial(AgileQuoteAdminProperty.Property.MaterialProperty oMaterialParameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateMaterial", ReplyAction="http://tempuri.org/IService1/UpdateMaterialResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/UpdateMaterialExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        int UpdateMaterial(AgileQuoteAdminProperty.Property.MaterialProperty oMaterialParameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteMaterial", ReplyAction="http://tempuri.org/IService1/DeleteMaterialResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/DeleteMaterialExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        string DeleteMaterial(int oMaterialId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CategoryList", ReplyAction="http://tempuri.org/IService1/CategoryListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/CategoryListExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        System.Collections.Generic.List<AgileQuoteAdminProperty.Property.CategoryProperty> CategoryList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SugectionMaterialMapping", ReplyAction="http://tempuri.org/IService1/SugectionMaterialMappingResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/SugectionMaterialMappingExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        string SugectionMaterialMapping(System.Collections.Generic.List<int> oMaterialList, int MaterialId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMaterialMappingSugectionMaterial", ReplyAction="http://tempuri.org/IService1/GetMaterialMappingSugectionMaterialResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/GetMaterialMappingSugectionMaterialExceptionClassFau" +
            "lt", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        System.Collections.Generic.List<AgileQuoteAdminProperty.Property.MaterialProperty> GetMaterialMappingSugectionMaterial(int MaterialId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteSugectionMaterial", ReplyAction="http://tempuri.org/IService1/DeleteSugectionMaterialResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/DeleteSugectionMaterialExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        string DeleteSugectionMaterial(int MaterialID, int MappingMaterial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/OfferedMaterialMapping", ReplyAction="http://tempuri.org/IService1/OfferedMaterialMappingResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/OfferedMaterialMappingExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        string OfferedMaterialMapping(System.Collections.Generic.List<int> oMaterialList, int MaterialId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMaterialMappingOfferedMaterial", ReplyAction="http://tempuri.org/IService1/GetMaterialMappingOfferedMaterialResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/GetMaterialMappingOfferedMaterialExceptionClassFault" +
            "", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        System.Collections.Generic.List<AgileQuoteAdminProperty.Property.MaterialProperty> GetMaterialMappingOfferedMaterial(int MaterialId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteOfferedMaterial", ReplyAction="http://tempuri.org/IService1/DeleteOfferedMaterialResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/DeleteOfferedMaterialExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        string DeleteOfferedMaterial(int MaterialID, int MappingMaterial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRentalProductsListService", ReplyAction="http://tempuri.org/IService1/GetRentalProductsListServiceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/GetRentalProductsListServiceExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        System.Collections.Generic.List<AgileQuoteAdminProperty.Property.RentalProductsProperty> GetRentalProductsListService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRentalProductsListByID", ReplyAction="http://tempuri.org/IService1/GetRentalProductsListByIDResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/GetRentalProductsListByIDExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        AgileQuoteAdminProperty.Property.RentalProductsProperty GetRentalProductsListByID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertRentalProducts", ReplyAction="http://tempuri.org/IService1/InsertRentalProductsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/InsertRentalProductsExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        int InsertRentalProducts(AgileQuoteAdminProperty.Property.RentalProductsProperty oRentalProductsParameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateRentalProducts", ReplyAction="http://tempuri.org/IService1/UpdateRentalProductsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/UpdateRentalProductsExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        int UpdateRentalProducts(AgileQuoteAdminProperty.Property.RentalProductsProperty oRentalProductsParameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteRentalProducts", ReplyAction="http://tempuri.org/IService1/DeleteRentalProductsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/DeleteRentalProductsExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        string DeleteRentalProducts(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMaterialBundleMapping", ReplyAction="http://tempuri.org/IService1/GetMaterialBundleMappingResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/GetMaterialBundleMappingExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        System.Collections.Generic.List<string> GetMaterialBundleMapping(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBundleListBasedOnCategory", ReplyAction="http://tempuri.org/IService1/GetBundleListBasedOnCategoryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/GetBundleListBasedOnCategoryExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        System.Collections.Generic.List<AgileQuoteAdminProperty.Property.BundleProperty> GetBundleListBasedOnCategory(string CategoryName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBundleMappingMaterial", ReplyAction="http://tempuri.org/IService1/GetBundleMappingMaterialResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/GetBundleMappingMaterialExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        System.Collections.Generic.List<AgileQuoteAdminProperty.Property.MaterialProperty> GetBundleMappingMaterial(int BundleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCategoryNameList", ReplyAction="http://tempuri.org/IService1/GetCategoryNameListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/GetCategoryNameListExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        System.Collections.Generic.List<string> GetCategoryNameList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMaterialListBasedOnCategory", ReplyAction="http://tempuri.org/IService1/GetMaterialListBasedOnCategoryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/GetMaterialListBasedOnCategoryExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        System.Collections.Generic.List<AgileQuoteAdminProperty.Property.MaterialProperty> GetMaterialListBasedOnCategory(string CategoryName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBundleSingleRecord", ReplyAction="http://tempuri.org/IService1/GetBundleSingleRecordResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/GetBundleSingleRecordExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        AgileQuoteAdminProperty.Property.BundleProperty GetBundleSingleRecord(int BundleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertMaterialMappingToBundle", ReplyAction="http://tempuri.org/IService1/InsertMaterialMappingToBundleResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/InsertMaterialMappingToBundleExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        string InsertMaterialMappingToBundle(System.Collections.Generic.Dictionary<int, int> MaterialIDQuantinyList, string BundleName, int UserID, string BundleDescription, int Warrenty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteBundleMaterialRecord", ReplyAction="http://tempuri.org/IService1/DeleteBundleMaterialRecordResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/DeleteBundleMaterialRecordExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        string DeleteBundleMaterialRecord(int BundleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateBundle", ReplyAction="http://tempuri.org/IService1/UpdateBundleResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/UpdateBundleExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        string UpdateBundle(System.Collections.Generic.Dictionary<int, int> MaterialIDQuantityList, string BundleName, string BundleDescription, int Warrenty, int BundleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UserRegistrationService", ReplyAction="http://tempuri.org/IService1/UserRegistrationServiceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/UserRegistrationServiceExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        string UserRegistrationService(AgileQuoteAdminProperty.Property.UserRegistration oUserReg, byte[] oUserImage, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CompanyNameService", ReplyAction="http://tempuri.org/IService1/CompanyNameServiceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/CompanyNameServiceExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        System.Collections.Generic.List<AgileQuoteAdminProperty.Property.CompanyValues> CompanyNameService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegistrationListService", ReplyAction="http://tempuri.org/IService1/RegistrationListServiceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/RegistrationListServiceExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        System.Collections.Generic.List<AgileQuoteAdminProperty.Property.RegistrationGrid> RegistrationListService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RoleNameService", ReplyAction="http://tempuri.org/IService1/RoleNameServiceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/RoleNameServiceExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        System.Collections.Generic.List<AgileQuoteAdminProperty.Property.UserRoleList> RoleNameService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SingleRegistrationService", ReplyAction="http://tempuri.org/IService1/SingleRegistrationServiceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/SingleRegistrationServiceExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        AgileQuoteAdminProperty.Property.RegistrationGrid SingleRegistrationService(int UserId, int CompanyCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateRegistrationService", ReplyAction="http://tempuri.org/IService1/UpdateRegistrationServiceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/UpdateRegistrationServiceExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        string UpdateRegistrationService(AgileQuoteAdminProperty.Property.RegistrationGrid oUserReg, byte[] oUserImage, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteRegistrationService", ReplyAction="http://tempuri.org/IService1/DeleteRegistrationServiceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/DeleteRegistrationServiceExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        string DeleteRegistrationService(int UserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetImageService", ReplyAction="http://tempuri.org/IService1/GetImageServiceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/GetImageServiceExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        System.Collections.Generic.List<AgileQuoteAdminProperty.Property.ImageProperty> GetImageService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCompanyNameService", ReplyAction="http://tempuri.org/IService1/GetCompanyNameServiceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/GetCompanyNameServiceExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        System.Collections.Generic.List<AgileQuoteAdminProperty.Property.CompanyProperty> GetCompanyNameService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSingleCompanyName", ReplyAction="http://tempuri.org/IService1/GetSingleCompanyNameResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/GetSingleCompanyNameExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        AgileQuoteAdminProperty.Property.CompanyProperty GetSingleCompanyName(int CompanyCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertCompanyNameService", ReplyAction="http://tempuri.org/IService1/InsertCompanyNameServiceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/InsertCompanyNameServiceExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        string InsertCompanyNameService(AgileQuoteAdminProperty.Property.CompanyProperty oCompanyProperty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCompanyNameService", ReplyAction="http://tempuri.org/IService1/UpdateCompanyNameServiceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/UpdateCompanyNameServiceExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        string UpdateCompanyNameService(AgileQuoteAdminProperty.Property.CompanyProperty oCompanyProperty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCompanyNameService", ReplyAction="http://tempuri.org/IService1/DeleteCompanyNameServiceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/DeleteCompanyNameServiceExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        string DeleteCompanyNameService(int CompanyCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckAuthentication", ReplyAction="http://tempuri.org/IService1/CheckAuthenticationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/CheckAuthenticationExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        bool CheckAuthentication(AgileQuoteAdminProperty.Property.LoginProperty oLogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserImage", ReplyAction="http://tempuri.org/IService1/GetUserImageResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/GetUserImageExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        byte[] GetUserImage(int UserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserName", ReplyAction="http://tempuri.org/IService1/GetUserNameResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/GetUserNameExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        System.Collections.Generic.Dictionary<int, string> GetUserName(AgileQuoteAdminProperty.Property.LoginProperty oLogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRulesList", ReplyAction="http://tempuri.org/IService1/GetRulesListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/GetRulesListExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        System.Collections.Generic.List<AgileQuoteAdminProperty.Property.RulesProperty> GetRulesList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSingleRule", ReplyAction="http://tempuri.org/IService1/GetSingleRuleResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/GetSingleRuleExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        AgileQuoteAdminProperty.Property.RulesProperty GetSingleRule(int RuleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertRule", ReplyAction="http://tempuri.org/IService1/InsertRuleResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/InsertRuleExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        string InsertRule(AgileQuoteAdminProperty.Property.RulesProperty oRulesProperty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateRule", ReplyAction="http://tempuri.org/IService1/UpdateRuleResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/UpdateRuleExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        string UpdateRule(AgileQuoteAdminProperty.Property.RulesProperty oRulesProperty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteRule", ReplyAction="http://tempuri.org/IService1/DeleteRuleResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/DeleteRuleExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        string DeleteRule(int RuleId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : AgileQuoteAdmin.AgileAdminService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<AgileQuoteAdmin.AgileAdminService.IService1>, AgileQuoteAdmin.AgileAdminService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string DeleteRentalSparsService(int RentalSparsId) {
            return base.Channel.DeleteRentalSparsService(RentalSparsId);
        }
        
        public int UpdateRentalSparsService(AgileQuoteAdminProperty.Property.RentalSparsProperty oRentalSpars) {
            return base.Channel.UpdateRentalSparsService(oRentalSpars);
        }
        
        public AgileQuoteAdminProperty.Property.RentalSparsProperty SingleRentalSparsService(int RentalSparsId) {
            return base.Channel.SingleRentalSparsService(RentalSparsId);
        }
        
        public System.Collections.Generic.List<AgileQuoteAdminProperty.Property.RentalSparsProperty> RentalSparsListService() {
            return base.Channel.RentalSparsListService();
        }
        
        public int InsertRentalSparsService(AgileQuoteAdminProperty.Property.RentalSparsProperty oRentalSpars) {
            return base.Channel.InsertRentalSparsService(oRentalSpars);
        }
        
        public System.Collections.Generic.List<AgileQuoteAdminProperty.Property.RoleProperty> GetRoleListService() {
            return base.Channel.GetRoleListService();
        }
        
        public AgileQuoteAdminProperty.Property.RoleProperty GetSingleRoleRecordService(int RoleId) {
            return base.Channel.GetSingleRoleRecordService(RoleId);
        }
        
        public string InsertRoleRecordService(AgileQuoteAdminProperty.Property.RoleProperty oRoleProperty) {
            return base.Channel.InsertRoleRecordService(oRoleProperty);
        }
        
        public string UpdateRoleService(AgileQuoteAdminProperty.Property.RoleProperty oRoleProperty) {
            return base.Channel.UpdateRoleService(oRoleProperty);
        }
        
        public string DeleteRoleService(int RoleID) {
            return base.Channel.DeleteRoleService(RoleID);
        }
        
        public System.Collections.Generic.List<AgileQuoteAdminProperty.Property.CurrencyProperty> GetCurrencyListService() {
            return base.Channel.GetCurrencyListService();
        }
        
        public AgileQuoteAdminProperty.Property.CurrencyProperty GetSingleCurrencyRecordService(int CurrencyId) {
            return base.Channel.GetSingleCurrencyRecordService(CurrencyId);
        }
        
        public string InsertCurrencyRecordService(AgileQuoteAdminProperty.Property.CurrencyProperty oCurrencyProperty) {
            return base.Channel.InsertCurrencyRecordService(oCurrencyProperty);
        }
        
        public string UpdateCurrencyService(AgileQuoteAdminProperty.Property.CurrencyProperty oCurrencyProperty) {
            return base.Channel.UpdateCurrencyService(oCurrencyProperty);
        }
        
        public string DeleteCurrrencyService(int CurrencyId) {
            return base.Channel.DeleteCurrrencyService(CurrencyId);
        }
        
        public System.Collections.Generic.List<AgileQuoteAdminProperty.Property.SalesOrganizationProperty> GetSalesOrganizationListService() {
            return base.Channel.GetSalesOrganizationListService();
        }
        
        public AgileQuoteAdminProperty.Property.SalesOrganizationProperty GetSalesOrganizationRecord(int SalesOrgCode) {
            return base.Channel.GetSalesOrganizationRecord(SalesOrgCode);
        }
        
        public string InsertRecordService(AgileQuoteAdminProperty.Property.SalesOrganizationProperty OsalesOrganizationProperty) {
            return base.Channel.InsertRecordService(OsalesOrganizationProperty);
        }
        
        public string UpdateRecordService(AgileQuoteAdminProperty.Property.SalesOrganizationProperty OsalesOrganizationProperty) {
            return base.Channel.UpdateRecordService(OsalesOrganizationProperty);
        }
        
        public string DeleteRecordService(int SalesOrgCode) {
            return base.Channel.DeleteRecordService(SalesOrgCode);
        }
        
        public System.Collections.Generic.List<AgileQuoteAdminProperty.Property.MaterialProperty> GetMaterialListService() {
            return base.Channel.GetMaterialListService();
        }
        
        public AgileQuoteAdminProperty.Property.MaterialProperty GetMaterialListByID(int oMaterialId) {
            return base.Channel.GetMaterialListByID(oMaterialId);
        }
        
        public int InsertMaterial(AgileQuoteAdminProperty.Property.MaterialProperty oMaterialParameter) {
            return base.Channel.InsertMaterial(oMaterialParameter);
        }
        
        public int UpdateMaterial(AgileQuoteAdminProperty.Property.MaterialProperty oMaterialParameter) {
            return base.Channel.UpdateMaterial(oMaterialParameter);
        }
        
        public string DeleteMaterial(int oMaterialId) {
            return base.Channel.DeleteMaterial(oMaterialId);
        }
        
        public System.Collections.Generic.List<AgileQuoteAdminProperty.Property.CategoryProperty> CategoryList() {
            return base.Channel.CategoryList();
        }
        
        public string SugectionMaterialMapping(System.Collections.Generic.List<int> oMaterialList, int MaterialId) {
            return base.Channel.SugectionMaterialMapping(oMaterialList, MaterialId);
        }
        
        public System.Collections.Generic.List<AgileQuoteAdminProperty.Property.MaterialProperty> GetMaterialMappingSugectionMaterial(int MaterialId) {
            return base.Channel.GetMaterialMappingSugectionMaterial(MaterialId);
        }
        
        public string DeleteSugectionMaterial(int MaterialID, int MappingMaterial) {
            return base.Channel.DeleteSugectionMaterial(MaterialID, MappingMaterial);
        }
        
        public string OfferedMaterialMapping(System.Collections.Generic.List<int> oMaterialList, int MaterialId) {
            return base.Channel.OfferedMaterialMapping(oMaterialList, MaterialId);
        }
        
        public System.Collections.Generic.List<AgileQuoteAdminProperty.Property.MaterialProperty> GetMaterialMappingOfferedMaterial(int MaterialId) {
            return base.Channel.GetMaterialMappingOfferedMaterial(MaterialId);
        }
        
        public string DeleteOfferedMaterial(int MaterialID, int MappingMaterial) {
            return base.Channel.DeleteOfferedMaterial(MaterialID, MappingMaterial);
        }
        
        public System.Collections.Generic.List<AgileQuoteAdminProperty.Property.RentalProductsProperty> GetRentalProductsListService() {
            return base.Channel.GetRentalProductsListService();
        }
        
        public AgileQuoteAdminProperty.Property.RentalProductsProperty GetRentalProductsListByID(int id) {
            return base.Channel.GetRentalProductsListByID(id);
        }
        
        public int InsertRentalProducts(AgileQuoteAdminProperty.Property.RentalProductsProperty oRentalProductsParameter) {
            return base.Channel.InsertRentalProducts(oRentalProductsParameter);
        }
        
        public int UpdateRentalProducts(AgileQuoteAdminProperty.Property.RentalProductsProperty oRentalProductsParameter) {
            return base.Channel.UpdateRentalProducts(oRentalProductsParameter);
        }
        
        public string DeleteRentalProducts(int ID) {
            return base.Channel.DeleteRentalProducts(ID);
        }
        
        public System.Collections.Generic.List<string> GetMaterialBundleMapping(string id) {
            return base.Channel.GetMaterialBundleMapping(id);
        }
        
        public System.Collections.Generic.List<AgileQuoteAdminProperty.Property.BundleProperty> GetBundleListBasedOnCategory(string CategoryName) {
            return base.Channel.GetBundleListBasedOnCategory(CategoryName);
        }
        
        public System.Collections.Generic.List<AgileQuoteAdminProperty.Property.MaterialProperty> GetBundleMappingMaterial(int BundleID) {
            return base.Channel.GetBundleMappingMaterial(BundleID);
        }
        
        public System.Collections.Generic.List<string> GetCategoryNameList() {
            return base.Channel.GetCategoryNameList();
        }
        
        public System.Collections.Generic.List<AgileQuoteAdminProperty.Property.MaterialProperty> GetMaterialListBasedOnCategory(string CategoryName) {
            return base.Channel.GetMaterialListBasedOnCategory(CategoryName);
        }
        
        public AgileQuoteAdminProperty.Property.BundleProperty GetBundleSingleRecord(int BundleID) {
            return base.Channel.GetBundleSingleRecord(BundleID);
        }
        
        public string InsertMaterialMappingToBundle(System.Collections.Generic.Dictionary<int, int> MaterialIDQuantinyList, string BundleName, int UserID, string BundleDescription, int Warrenty) {
            return base.Channel.InsertMaterialMappingToBundle(MaterialIDQuantinyList, BundleName, UserID, BundleDescription, Warrenty);
        }
        
        public string DeleteBundleMaterialRecord(int BundleID) {
            return base.Channel.DeleteBundleMaterialRecord(BundleID);
        }
        
        public string UpdateBundle(System.Collections.Generic.Dictionary<int, int> MaterialIDQuantityList, string BundleName, string BundleDescription, int Warrenty, int BundleID) {
            return base.Channel.UpdateBundle(MaterialIDQuantityList, BundleName, BundleDescription, Warrenty, BundleID);
        }
        
        public string UserRegistrationService(AgileQuoteAdminProperty.Property.UserRegistration oUserReg, byte[] oUserImage, string name) {
            return base.Channel.UserRegistrationService(oUserReg, oUserImage, name);
        }
        
        public System.Collections.Generic.List<AgileQuoteAdminProperty.Property.CompanyValues> CompanyNameService() {
            return base.Channel.CompanyNameService();
        }
        
        public System.Collections.Generic.List<AgileQuoteAdminProperty.Property.RegistrationGrid> RegistrationListService() {
            return base.Channel.RegistrationListService();
        }
        
        public System.Collections.Generic.List<AgileQuoteAdminProperty.Property.UserRoleList> RoleNameService() {
            return base.Channel.RoleNameService();
        }
        
        public AgileQuoteAdminProperty.Property.RegistrationGrid SingleRegistrationService(int UserId, int CompanyCode) {
            return base.Channel.SingleRegistrationService(UserId, CompanyCode);
        }
        
        public string UpdateRegistrationService(AgileQuoteAdminProperty.Property.RegistrationGrid oUserReg, byte[] oUserImage, string name) {
            return base.Channel.UpdateRegistrationService(oUserReg, oUserImage, name);
        }
        
        public string DeleteRegistrationService(int UserId) {
            return base.Channel.DeleteRegistrationService(UserId);
        }
        
        public System.Collections.Generic.List<AgileQuoteAdminProperty.Property.ImageProperty> GetImageService() {
            return base.Channel.GetImageService();
        }
        
        public System.Collections.Generic.List<AgileQuoteAdminProperty.Property.CompanyProperty> GetCompanyNameService() {
            return base.Channel.GetCompanyNameService();
        }
        
        public AgileQuoteAdminProperty.Property.CompanyProperty GetSingleCompanyName(int CompanyCode) {
            return base.Channel.GetSingleCompanyName(CompanyCode);
        }
        
        public string InsertCompanyNameService(AgileQuoteAdminProperty.Property.CompanyProperty oCompanyProperty) {
            return base.Channel.InsertCompanyNameService(oCompanyProperty);
        }
        
        public string UpdateCompanyNameService(AgileQuoteAdminProperty.Property.CompanyProperty oCompanyProperty) {
            return base.Channel.UpdateCompanyNameService(oCompanyProperty);
        }
        
        public string DeleteCompanyNameService(int CompanyCode) {
            return base.Channel.DeleteCompanyNameService(CompanyCode);
        }
        
        public bool CheckAuthentication(AgileQuoteAdminProperty.Property.LoginProperty oLogin) {
            return base.Channel.CheckAuthentication(oLogin);
        }
        
        public byte[] GetUserImage(int UserId) {
            return base.Channel.GetUserImage(UserId);
        }
        
        public System.Collections.Generic.Dictionary<int, string> GetUserName(AgileQuoteAdminProperty.Property.LoginProperty oLogin) {
            return base.Channel.GetUserName(oLogin);
        }
        
        public System.Collections.Generic.List<AgileQuoteAdminProperty.Property.RulesProperty> GetRulesList() {
            return base.Channel.GetRulesList();
        }
        
        public AgileQuoteAdminProperty.Property.RulesProperty GetSingleRule(int RuleId) {
            return base.Channel.GetSingleRule(RuleId);
        }
        
        public string InsertRule(AgileQuoteAdminProperty.Property.RulesProperty oRulesProperty) {
            return base.Channel.InsertRule(oRulesProperty);
        }
        
        public string UpdateRule(AgileQuoteAdminProperty.Property.RulesProperty oRulesProperty) {
            return base.Channel.UpdateRule(oRulesProperty);
        }
        
        public string DeleteRule(int RuleId) {
            return base.Channel.DeleteRule(RuleId);
        }
    }
}
