//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgileQuoteAdmin.CurrencyReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CurrencyReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateRentalProducts", ReplyAction="http://tempuri.org/IService1/UpdateRentalProductsResponse")]
        int UpdateRentalProducts(AgileQuoteAdminProperty.Property.RentalProductsProperty oRentalProductsParameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteRentalProducts", ReplyAction="http://tempuri.org/IService1/DeleteRentalProductsResponse")]
        string DeleteRentalProducts(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateBundle", ReplyAction="http://tempuri.org/IService1/CreateBundleResponse")]
        string CreateBundle(string BundleName, string Catagory, System.Collections.Generic.List<string> FromMaterialID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateBundle", ReplyAction="http://tempuri.org/IService1/UpdateBundleResponse")]
        string UpdateBundle(string BundleName, System.Collections.Generic.List<string> FromMaterialID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBundleListService", ReplyAction="http://tempuri.org/IService1/GetBundleListServiceResponse")]
        System.Collections.Generic.List<AgileQuoteAdminProperty.Property.BundleProperty> GetBundleListService(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMaterialBundleMapping", ReplyAction="http://tempuri.org/IService1/GetMaterialBundleMappingResponse")]
        System.Collections.Generic.List<string> GetMaterialBundleMapping(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BundleEdit", ReplyAction="http://tempuri.org/IService1/BundleEditResponse")]
        string BundleEdit(AgileQuoteAdminProperty.Property.BundleProperty oBundleProperty, string MaterialIDList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UserRegistrationService", ReplyAction="http://tempuri.org/IService1/UserRegistrationServiceResponse")]
        string UserRegistrationService(AgileQuoteAdminProperty.Property.UserRegistration oUserReg, byte[] oUserImage, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CompanyNameService", ReplyAction="http://tempuri.org/IService1/CompanyNameServiceResponse")]
        System.Collections.Generic.List<AgileQuoteAdminProperty.Property.CompanyValues> CompanyNameService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegistrationListService", ReplyAction="http://tempuri.org/IService1/RegistrationListServiceResponse")]
        System.Collections.Generic.List<AgileQuoteAdminProperty.Property.RegistrationGrid> RegistrationListService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RoleNameService", ReplyAction="http://tempuri.org/IService1/RoleNameServiceResponse")]
        System.Collections.Generic.List<AgileQuoteAdminProperty.Property.UserRoleList> RoleNameService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SingleRegistrationService", ReplyAction="http://tempuri.org/IService1/SingleRegistrationServiceResponse")]
        AgileQuoteAdminProperty.Property.RegistrationGrid SingleRegistrationService(int UserId, int CompanyCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateRegistrationService", ReplyAction="http://tempuri.org/IService1/UpdateRegistrationServiceResponse")]
        string UpdateRegistrationService(AgileQuoteAdminProperty.Property.RegistrationGrid oUserReg, byte[] oUserImage, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteRegistrationService", ReplyAction="http://tempuri.org/IService1/DeleteRegistrationServiceResponse")]
        string DeleteRegistrationService(int UserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetImageService", ReplyAction="http://tempuri.org/IService1/GetImageServiceResponse")]
        System.Collections.Generic.List<AgileQuoteAdminProperty.Property.ImageProperty> GetImageService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCompanyNameService", ReplyAction="http://tempuri.org/IService1/GetCompanyNameServiceResponse")]
        System.Collections.Generic.List<AgileQuoteAdminProperty.Property.CompanyProperty> GetCompanyNameService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSingleCompanyName", ReplyAction="http://tempuri.org/IService1/GetSingleCompanyNameResponse")]
        AgileQuoteAdminProperty.Property.CompanyProperty GetSingleCompanyName(int CompanyCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertCompanyNameService", ReplyAction="http://tempuri.org/IService1/InsertCompanyNameServiceResponse")]
        string InsertCompanyNameService(AgileQuoteAdminProperty.Property.CompanyProperty oCompanyProperty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCompanyNameService", ReplyAction="http://tempuri.org/IService1/UpdateCompanyNameServiceResponse")]
        string UpdateCompanyNameService(AgileQuoteAdminProperty.Property.CompanyProperty oCompanyProperty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCompanyNameService", ReplyAction="http://tempuri.org/IService1/DeleteCompanyNameServiceResponse")]
        string DeleteCompanyNameService(int CompanyCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckAuthentication", ReplyAction="http://tempuri.org/IService1/CheckAuthenticationResponse")]
        bool CheckAuthentication(AgileQuoteAdminProperty.Property.LoginProperty oLogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserImage", ReplyAction="http://tempuri.org/IService1/GetUserImageResponse")]
        byte[] GetUserImage(int UserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserName", ReplyAction="http://tempuri.org/IService1/GetUserNameResponse")]
        System.Collections.Generic.Dictionary<int, string> GetUserName(AgileQuoteAdminProperty.Property.LoginProperty oLogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteRentalSparsService", ReplyAction="http://tempuri.org/IService1/DeleteRentalSparsServiceResponse")]
        string DeleteRentalSparsService(int RentalSparsId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateRentalSparsService", ReplyAction="http://tempuri.org/IService1/UpdateRentalSparsServiceResponse")]
        int UpdateRentalSparsService(AgileQuoteAdminProperty.Property.RentalSparsProperty oRentalSpars);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SingleRentalSparsService", ReplyAction="http://tempuri.org/IService1/SingleRentalSparsServiceResponse")]
        AgileQuoteAdminProperty.Property.RentalSparsProperty SingleRentalSparsService(int RentalSparsId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RentalSparsListService", ReplyAction="http://tempuri.org/IService1/RentalSparsListServiceResponse")]
        System.Collections.Generic.List<AgileQuoteAdminProperty.Property.RentalSparsProperty> RentalSparsListService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertRentalSparsService", ReplyAction="http://tempuri.org/IService1/InsertRentalSparsServiceResponse")]
        int InsertRentalSparsService(AgileQuoteAdminProperty.Property.RentalSparsProperty oRentalSpars);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRoleListService", ReplyAction="http://tempuri.org/IService1/GetRoleListServiceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/GetRoleListServiceExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        System.Collections.Generic.List<AgileQuoteAdminProperty.Property.RoleProperty> GetRoleListService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSingleRoleRecordService", ReplyAction="http://tempuri.org/IService1/GetSingleRoleRecordServiceResponse")]
        AgileQuoteAdminProperty.Property.RoleProperty GetSingleRoleRecordService(int RoleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertRoleRecordService", ReplyAction="http://tempuri.org/IService1/InsertRoleRecordServiceResponse")]
        string InsertRoleRecordService(AgileQuoteAdminProperty.Property.RoleProperty rp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateRoleService", ReplyAction="http://tempuri.org/IService1/UpdateRoleServiceResponse")]
        string UpdateRoleService(AgileQuoteAdminProperty.Property.RoleProperty rp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteRoleService", ReplyAction="http://tempuri.org/IService1/DeleteRoleServiceResponse")]
        string DeleteRoleService(int RoleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCurrencyListService", ReplyAction="http://tempuri.org/IService1/GetCurrencyListServiceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/GetCurrencyListServiceExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        System.Collections.Generic.List<AgileQuoteAdminProperty.Property.CurrencyProperty> GetCurrencyListService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSingleCurrencyRecordService", ReplyAction="http://tempuri.org/IService1/GetSingleCurrencyRecordServiceResponse")]
        AgileQuoteAdminProperty.Property.CurrencyProperty GetSingleCurrencyRecordService(int CurrencyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertCurrencyRecordService", ReplyAction="http://tempuri.org/IService1/InsertCurrencyRecordServiceResponse")]
        string InsertCurrencyRecordService(AgileQuoteAdminProperty.Property.CurrencyProperty cp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCurrencyService", ReplyAction="http://tempuri.org/IService1/UpdateCurrencyServiceResponse")]
        string UpdateCurrencyService(AgileQuoteAdminProperty.Property.CurrencyProperty cp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCurrrencyService", ReplyAction="http://tempuri.org/IService1/DeleteCurrrencyServiceResponse")]
        string DeleteCurrrencyService(int CurrencyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSalesOrganizationListService", ReplyAction="http://tempuri.org/IService1/GetSalesOrganizationListServiceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AgileQuoteAdminProperty.Property.ExceptionClass), Action="http://tempuri.org/IService1/GetSalesOrganizationListServiceExceptionClassFault", Name="ExceptionClass", Namespace="http://schemas.datacontract.org/2004/07/AgileQuoteAdminProperty.Property")]
        System.Collections.Generic.List<AgileQuoteAdminProperty.Property.SalesOrganizationProperty> GetSalesOrganizationListService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSalesOrganizationRecord", ReplyAction="http://tempuri.org/IService1/GetSalesOrganizationRecordResponse")]
        AgileQuoteAdminProperty.Property.SalesOrganizationProperty GetSalesOrganizationRecord(int SalesOrgCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertRecordService", ReplyAction="http://tempuri.org/IService1/InsertRecordServiceResponse")]
        string InsertRecordService(AgileQuoteAdminProperty.Property.SalesOrganizationProperty OsalesOrganizationProperty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateRecordService", ReplyAction="http://tempuri.org/IService1/UpdateRecordServiceResponse")]
        string UpdateRecordService(AgileQuoteAdminProperty.Property.SalesOrganizationProperty OsalesOrganizationProperty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteRecordService", ReplyAction="http://tempuri.org/IService1/DeleteRecordServiceResponse")]
        string DeleteRecordService(int SalesOrgCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMaterialListService", ReplyAction="http://tempuri.org/IService1/GetMaterialListServiceResponse")]
        System.Collections.Generic.List<AgileQuoteAdminProperty.Property.MaterialProperty> GetMaterialListService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMaterialListByID", ReplyAction="http://tempuri.org/IService1/GetMaterialListByIDResponse")]
        AgileQuoteAdminProperty.Property.MaterialProperty GetMaterialListByID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertMaterial", ReplyAction="http://tempuri.org/IService1/InsertMaterialResponse")]
        int InsertMaterial(AgileQuoteAdminProperty.Property.MaterialProperty oMaterialParameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateMaterial", ReplyAction="http://tempuri.org/IService1/UpdateMaterialResponse")]
        int UpdateMaterial(AgileQuoteAdminProperty.Property.MaterialProperty oMaterialParameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteMaterial", ReplyAction="http://tempuri.org/IService1/DeleteMaterialResponse")]
        string DeleteMaterial(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRentalProductsListService", ReplyAction="http://tempuri.org/IService1/GetRentalProductsListServiceResponse")]
        System.Collections.Generic.List<AgileQuoteAdminProperty.Property.RentalProductsProperty> GetRentalProductsListService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRentalProductsListByID", ReplyAction="http://tempuri.org/IService1/GetRentalProductsListByIDResponse")]
        AgileQuoteAdminProperty.Property.RentalProductsProperty GetRentalProductsListByID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertRentalProducts", ReplyAction="http://tempuri.org/IService1/InsertRentalProductsResponse")]
        int InsertRentalProducts(AgileQuoteAdminProperty.Property.RentalProductsProperty oRentalProductsParameter);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : AgileQuoteAdmin.CurrencyReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<AgileQuoteAdmin.CurrencyReference.IService1>, AgileQuoteAdmin.CurrencyReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int UpdateRentalProducts(AgileQuoteAdminProperty.Property.RentalProductsProperty oRentalProductsParameter) {
            return base.Channel.UpdateRentalProducts(oRentalProductsParameter);
        }
        
        public string DeleteRentalProducts(int ID) {
            return base.Channel.DeleteRentalProducts(ID);
        }
        
        public string CreateBundle(string BundleName, string Catagory, System.Collections.Generic.List<string> FromMaterialID) {
            return base.Channel.CreateBundle(BundleName, Catagory, FromMaterialID);
        }
        
        public string UpdateBundle(string BundleName, System.Collections.Generic.List<string> FromMaterialID) {
            return base.Channel.UpdateBundle(BundleName, FromMaterialID);
        }
        
        public System.Collections.Generic.List<AgileQuoteAdminProperty.Property.BundleProperty> GetBundleListService(string id) {
            return base.Channel.GetBundleListService(id);
        }
        
        public System.Collections.Generic.List<string> GetMaterialBundleMapping(string id) {
            return base.Channel.GetMaterialBundleMapping(id);
        }
        
        public string BundleEdit(AgileQuoteAdminProperty.Property.BundleProperty oBundleProperty, string MaterialIDList) {
            return base.Channel.BundleEdit(oBundleProperty, MaterialIDList);
        }
        
        public string UserRegistrationService(AgileQuoteAdminProperty.Property.UserRegistration oUserReg, byte[] oUserImage, string name) {
            return base.Channel.UserRegistrationService(oUserReg, oUserImage, name);
        }
        
        public System.Collections.Generic.List<AgileQuoteAdminProperty.Property.CompanyValues> CompanyNameService() {
            return base.Channel.CompanyNameService();
        }
        
        public System.Collections.Generic.List<AgileQuoteAdminProperty.Property.RegistrationGrid> RegistrationListService() {
            return base.Channel.RegistrationListService();
        }
        
        public System.Collections.Generic.List<AgileQuoteAdminProperty.Property.UserRoleList> RoleNameService() {
            return base.Channel.RoleNameService();
        }
        
        public AgileQuoteAdminProperty.Property.RegistrationGrid SingleRegistrationService(int UserId, int CompanyCode) {
            return base.Channel.SingleRegistrationService(UserId, CompanyCode);
        }
        
        public string UpdateRegistrationService(AgileQuoteAdminProperty.Property.RegistrationGrid oUserReg, byte[] oUserImage, string name) {
            return base.Channel.UpdateRegistrationService(oUserReg, oUserImage, name);
        }
        
        public string DeleteRegistrationService(int UserId) {
            return base.Channel.DeleteRegistrationService(UserId);
        }
        
        public System.Collections.Generic.List<AgileQuoteAdminProperty.Property.ImageProperty> GetImageService() {
            return base.Channel.GetImageService();
        }
        
        public System.Collections.Generic.List<AgileQuoteAdminProperty.Property.CompanyProperty> GetCompanyNameService() {
            return base.Channel.GetCompanyNameService();
        }
        
        public AgileQuoteAdminProperty.Property.CompanyProperty GetSingleCompanyName(int CompanyCode) {
            return base.Channel.GetSingleCompanyName(CompanyCode);
        }
        
        public string InsertCompanyNameService(AgileQuoteAdminProperty.Property.CompanyProperty oCompanyProperty) {
            return base.Channel.InsertCompanyNameService(oCompanyProperty);
        }
        
        public string UpdateCompanyNameService(AgileQuoteAdminProperty.Property.CompanyProperty oCompanyProperty) {
            return base.Channel.UpdateCompanyNameService(oCompanyProperty);
        }
        
        public string DeleteCompanyNameService(int CompanyCode) {
            return base.Channel.DeleteCompanyNameService(CompanyCode);
        }
        
        public bool CheckAuthentication(AgileQuoteAdminProperty.Property.LoginProperty oLogin) {
            return base.Channel.CheckAuthentication(oLogin);
        }
        
        public byte[] GetUserImage(int UserId) {
            return base.Channel.GetUserImage(UserId);
        }
        
        public System.Collections.Generic.Dictionary<int, string> GetUserName(AgileQuoteAdminProperty.Property.LoginProperty oLogin) {
            return base.Channel.GetUserName(oLogin);
        }
        
        public string DeleteRentalSparsService(int RentalSparsId) {
            return base.Channel.DeleteRentalSparsService(RentalSparsId);
        }
        
        public int UpdateRentalSparsService(AgileQuoteAdminProperty.Property.RentalSparsProperty oRentalSpars) {
            return base.Channel.UpdateRentalSparsService(oRentalSpars);
        }
        
        public AgileQuoteAdminProperty.Property.RentalSparsProperty SingleRentalSparsService(int RentalSparsId) {
            return base.Channel.SingleRentalSparsService(RentalSparsId);
        }
        
        public System.Collections.Generic.List<AgileQuoteAdminProperty.Property.RentalSparsProperty> RentalSparsListService() {
            return base.Channel.RentalSparsListService();
        }
        
        public int InsertRentalSparsService(AgileQuoteAdminProperty.Property.RentalSparsProperty oRentalSpars) {
            return base.Channel.InsertRentalSparsService(oRentalSpars);
        }
        
        public System.Collections.Generic.List<AgileQuoteAdminProperty.Property.RoleProperty> GetRoleListService() {
            return base.Channel.GetRoleListService();
        }
        
        public AgileQuoteAdminProperty.Property.RoleProperty GetSingleRoleRecordService(int RoleId) {
            return base.Channel.GetSingleRoleRecordService(RoleId);
        }
        
        public string InsertRoleRecordService(AgileQuoteAdminProperty.Property.RoleProperty rp) {
            return base.Channel.InsertRoleRecordService(rp);
        }
        
        public string UpdateRoleService(AgileQuoteAdminProperty.Property.RoleProperty rp) {
            return base.Channel.UpdateRoleService(rp);
        }
        
        public string DeleteRoleService(int RoleID) {
            return base.Channel.DeleteRoleService(RoleID);
        }
        
        public System.Collections.Generic.List<AgileQuoteAdminProperty.Property.CurrencyProperty> GetCurrencyListService() {
            return base.Channel.GetCurrencyListService();
        }
        
        public AgileQuoteAdminProperty.Property.CurrencyProperty GetSingleCurrencyRecordService(int CurrencyId) {
            return base.Channel.GetSingleCurrencyRecordService(CurrencyId);
        }
        
        public string InsertCurrencyRecordService(AgileQuoteAdminProperty.Property.CurrencyProperty cp) {
            return base.Channel.InsertCurrencyRecordService(cp);
        }
        
        public string UpdateCurrencyService(AgileQuoteAdminProperty.Property.CurrencyProperty cp) {
            return base.Channel.UpdateCurrencyService(cp);
        }
        
        public string DeleteCurrrencyService(int CurrencyId) {
            return base.Channel.DeleteCurrrencyService(CurrencyId);
        }
        
        public System.Collections.Generic.List<AgileQuoteAdminProperty.Property.SalesOrganizationProperty> GetSalesOrganizationListService() {
            return base.Channel.GetSalesOrganizationListService();
        }
        
        public AgileQuoteAdminProperty.Property.SalesOrganizationProperty GetSalesOrganizationRecord(int SalesOrgCode) {
            return base.Channel.GetSalesOrganizationRecord(SalesOrgCode);
        }
        
        public string InsertRecordService(AgileQuoteAdminProperty.Property.SalesOrganizationProperty OsalesOrganizationProperty) {
            return base.Channel.InsertRecordService(OsalesOrganizationProperty);
        }
        
        public string UpdateRecordService(AgileQuoteAdminProperty.Property.SalesOrganizationProperty OsalesOrganizationProperty) {
            return base.Channel.UpdateRecordService(OsalesOrganizationProperty);
        }
        
        public string DeleteRecordService(int SalesOrgCode) {
            return base.Channel.DeleteRecordService(SalesOrgCode);
        }
        
        public System.Collections.Generic.List<AgileQuoteAdminProperty.Property.MaterialProperty> GetMaterialListService() {
            return base.Channel.GetMaterialListService();
        }
        
        public AgileQuoteAdminProperty.Property.MaterialProperty GetMaterialListByID(int id) {
            return base.Channel.GetMaterialListByID(id);
        }
        
        public int InsertMaterial(AgileQuoteAdminProperty.Property.MaterialProperty oMaterialParameter) {
            return base.Channel.InsertMaterial(oMaterialParameter);
        }
        
        public int UpdateMaterial(AgileQuoteAdminProperty.Property.MaterialProperty oMaterialParameter) {
            return base.Channel.UpdateMaterial(oMaterialParameter);
        }
        
        public string DeleteMaterial(int ID) {
            return base.Channel.DeleteMaterial(ID);
        }
        
        public System.Collections.Generic.List<AgileQuoteAdminProperty.Property.RentalProductsProperty> GetRentalProductsListService() {
            return base.Channel.GetRentalProductsListService();
        }
        
        public AgileQuoteAdminProperty.Property.RentalProductsProperty GetRentalProductsListByID(int id) {
            return base.Channel.GetRentalProductsListByID(id);
        }
        
        public int InsertRentalProducts(AgileQuoteAdminProperty.Property.RentalProductsProperty oRentalProductsParameter) {
            return base.Channel.InsertRentalProducts(oRentalProductsParameter);
        }
    }
}
